spring:
  application:
    name: 2025_bucket
  jpa:
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/mp_db
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
